### ISSUE TITLE
AUTHORS

### ISSUE THREAD

**Issue by hgees** [hgees/grafodirigido02#1]
Pessoal, conforme vão aceitando o convite para colaborar com o repositório, por favor adicionem seus dados no arquivo AUTHORS.

Obrigado!!

**Comment by priscilasousa** [comment]
adicionado com sucesso!

**Comment by mmcpininga** [comment]
Feito!

**Comment by thiagooqueiroz** [comment]
adicionado

**Comment by marinacollier** [comment]
Adicionado!!

**Comment by dmfds** [comment]
Feito!

**Comment by hgees** [comment]
FEITO!!
