### ISSUE TITLE
ex9: mudança para abrir o arquivo txt

### ISSUE THREAD

**Issue by ricardodimas** [hgees/grafodirigido02#4]
Pessoal, fiz umas mudanças no código. Pra rodar o programa abrindo o arquivo txt é só colocar: 
        $ ex9.x entrada.txt
Fiz isso porque foi a maneira que eu achei pra que ele abrisse o arquivo e contasse o número de linhas do arquivo texto.

**Comment by mmcpininga** [comment]
No caso seria `$ ./ex9.x entrada.txt`, não é?

**Comment by bituco** [comment]
Não seria melhor usar uma chave?

**Comment by ricardodimas** [comment]
Corrgido, @mmcpininga

**Comment by hgees** [comment]
Feito
