### ISSUE TITLE
Ideia para critério de parada

### ISSUE THREAD

**Issue by ricardodimas** [hgees/grafodirigido02#5]
Pessoal, a gente precisa de um critério de parada pra ele parar ler o arquivo txt e criar a imagem bmp. Eu tô pensando em usar o número de linhas do arquivo txt para isso. O que vocês acham?

**Comment by hgees** [comment]
Eu acho legal usar enquanto o fgets for diferente de EOF (End Of File)

**Comment by ricardodimas** [comment]
Pode ser também

**Comment by bmhori** [comment]
o numero de linhas pode variar?
Se sim, eu acho mais interessante utilizar a ideia proposta por hericles.

**Comment by hgees** [comment]
Ideia já implementada
